'use client';
import { useCallback, useEffect, useState } from 'react';
import { Activity, ArrowDownToLine, BarChart3, Database, Play, RefreshCw, Settings2 } from 'lucide-react';

type Archive = {interval:string;instruments:number;candles:number};
type Job = {id:string;kind:string;status:string;progress:number;total:number;result?:any;error?:string};
type Coverage = {instrument:string;interval:string;from_date:string;to_date:string;candles:number};
const intervals=['1m','5m','15m','30m','1h','1d','1w','1mo'];
const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
const earlier=new Date(Date.now()-365*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
function errorMessage(value:unknown):string {if(typeof value==='string')return value;if(Array.isArray(value))return value.map(errorMessage).join('; ');if(value&&typeof value==='object'){const detail=value as {msg?:unknown;message?:unknown;detail?:unknown};return errorMessage(detail.msg??detail.message??detail.detail??'Request failed')}return 'Request failed'}
async function api(path:string, body?:unknown) { const r=await fetch(`/api/${path}`,body ? {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(errorMessage(data.detail??data));return data; }
export default function Home(){
 const [tab,setTab]=useState<'archive'|'backtest'>('archive');
 const [status,setStatus]=useState<{archive:Archive[];active_jobs:number}|null>(null);
 const [coverage,setCoverage]=useState<Coverage[]>([]);
 const [error,setError]=useState('');const [notice,setNotice]=useState('');const [job,setJob]=useState<Job|null>(null);
 const [symbols,setSymbols]=useState('NSE_EQ|INE002A01018');const [selected,setSelected]=useState<string[]>(['1m','5m','15m','30m','1h','1d','1w','1mo']);
 const [from,setFrom]=useState(earlier);const [to,setTo]=useState(today);const [period,setPeriod]=useState('1m');const [strategy,setStrategy]=useState('dip_buy');
 const [dip,setDip]=useState('3');const [target,setTarget]=useState('2');const [stop,setStop]=useState('1');const [capital,setCapital]=useState('10000');const [fast,setFast]=useState('10');const [slow,setSlow]=useState('30');
 const refresh=useCallback(async()=>{try { const [a,b]=await Promise.all([api('status'),api('symbols')]);setStatus(a);setCoverage(b.symbols);setError(''); }catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{refresh();const saved=localStorage.getItem('backtest-desk-job');if(saved)api(`jobs/${saved}`).then(setJob).catch(()=>localStorage.removeItem('backtest-desk-job'))},[refresh]);
 useEffect(()=>{if(job?.id)localStorage.setItem('backtest-desk-job',job.id)},[job?.id]);
 useEffect(()=>{if(!job||!['queued','running'].includes(job.status))return;const timer=setInterval(async()=>{try{const next=await api(`jobs/${job.id}`);setJob(next);if(next.status==='complete'){setNotice(next.kind==='backfill'?'Import completed.':'Backtest completed.');refresh();}if(next.status==='failed')setError(next.error||'Job failed');}catch(e){setError((e as Error).message)}},2000);return()=>clearInterval(timer)},[job,refresh]);
 function parsed(){return [...new Set(symbols.split(/[\s,]+/).map(s=>s.trim()).filter(Boolean))]}
 async function submit(kind:'backfill'|'backtests'){setError('');setNotice('');if(!parsed().length){setError('Add at least one ticker or instrument key.');return}try{const payload=kind==='backfill'?{instruments:parsed(),intervals:selected,from_date:from,to_date:to}:{instruments:parsed(),interval:period,from_date:from,to_date:to,strategy,dip_pct:Number(dip),target_pct:Number(target),stop_pct:Number(stop),capital_per_trade:Number(capital),fast:Number(fast),slow:Number(slow)};const result=await api(kind,payload);setJob({...result,kind,progress:0,total:0});setNotice('Job queued. This browser will restore the latest job when you return.');}catch(e){setError((e as Error).message)}}
 function downloadTrades(){if(!job?.result?.trades)return;const t=job.result.trades;const cols=['instrument','entry_at','entry','exit_at','exit','quantity','reason','pnl','return_pct'];const csv=[cols.join(','),...t.map((r:Record<string,unknown>)=>cols.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download=`backtest-${job.id}.csv`;link.click();URL.revokeObjectURL(link.href)}
 const total=status?.archive.reduce((sum,a)=>sum+a.candles,0)||0;
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandmark"><BarChart3 size={21}/></div><div><strong>BACKTEST DESK</strong><span>UPSTOX RESEARCH</span></div></div><div className="navlabel">WORKSPACE</div><button className={`nav ${tab==='archive'?'active':''}`} onClick={()=>setTab('archive')}><Database size={18}/> Data archive</button><button className={`nav ${tab==='backtest'?'active':''}`} onClick={()=>setTab('backtest')}><Activity size={18}/> Backtests</button><div className="sidebarbottom"><span className={`statusdot ${status?'online':''}`}/>{status?'Worker connected':'Worker unavailable'}<small>Data stays on the server</small></div></aside>
 <main className="main"><header className="topbar"><div className="crumb">RESEARCH / {tab==='archive'?'DATA ARCHIVE':'BACKTESTS'}</div><button className="iconbutton" onClick={refresh} aria-label="Refresh data"><RefreshCw size={17}/></button></header>
 <div className="content"><div className="heading"><div><div className="eyebrow">MARKET DATA WORKSPACE</div><h1>{tab==='archive'?'Data archive':'Strategy backtests'}</h1><p>{tab==='archive'?'Import Upstox candles and keep each timeframe in its own Parquet dataset.':'Run candle-based strategies against your stored data.'}</p></div><div className="timebadge">NSE · ASIA/KOLKATA</div></div>
 {error&&<div className="alert danger" role="alert">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="metrics"><div className="metric"><span>STORED CANDLES</span><strong>{total.toLocaleString()}</strong><small>Across all timeframes</small></div><div className="metric"><span>INSTRUMENTS</span><strong>{new Set(coverage.map(x=>x.instrument)).size}</strong><small>With archived data</small></div><div className="metric"><span>ACTIVE JOBS</span><strong>{status?.active_jobs??'—'}</strong><small>Queued or running</small></div></div>
 <div className="grid"><section className="panel controls"><div className="panelheading"><span className="panelicon"><Settings2 size={18}/></span><div><h2>{tab==='archive'?'New data import':'Configure run'}</h2><p>{tab==='archive'?'Existing windows are skipped on repeat imports.':'Signals execute at the following candle open.'}</p></div></div>
 <label>NSE TICKERS OR UPSTOX INSTRUMENT KEYS<textarea value={symbols} onChange={e=>setSymbols(e.target.value)} rows={3} placeholder="RELIANCE, TCS or NSE_EQ|INE002A01018"/><small>Separate entries with commas, spaces, or new lines. Tickers resolve to NSE equities.</small></label>
 <div className="fields"><label>FROM<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>TO<input type="date" value={to} min={from} max={today} onChange={e=>setTo(e.target.value)}/></label></div>
 {tab==='archive'?<><div className="fieldtitle">TIMEFRAMES <span>{selected.length} selected</span></div><div className="chips">{intervals.map(p=><button key={p} className={`chip ${selected.includes(p)?'chosen':''}`} onClick={()=>setSelected(selected.includes(p)?selected.filter(v=>v!==p):[...selected,p])}>{p}</button>)}</div><button className="primary" disabled={!selected.length||!!job&&['queued','running'].includes(job.status)} onClick={()=>submit('backfill')}><ArrowDownToLine size={17}/> Start import</button></>:<><div className="fields"><label>TIMEFRAME<select value={period} onChange={e=>setPeriod(e.target.value)}>{intervals.map(p=><option key={p}>{p}</option>)}</select></label><label>STRATEGY<select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="dip_buy">Dip from previous close</option><option value="sma_cross">SMA crossover</option></select></label></div>{strategy==='dip_buy'?<div className="fields three"><label>DIP %<input type="number" min="0.1" step="0.1" value={dip} onChange={e=>setDip(e.target.value)}/></label><label>TARGET %<input type="number" min="0.1" step="0.1" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>STOP %<input type="number" min="0.1" step="0.1" value={stop} onChange={e=>setStop(e.target.value)}/></label></div>:<div className="fields three"><label>FAST SMA<input type="number" min="2" value={fast} onChange={e=>setFast(e.target.value)}/></label><label>SLOW SMA<input type="number" min="3" value={slow} onChange={e=>setSlow(e.target.value)}/></label><label>STOP %<input type="number" min="0.1" step="0.1" value={stop} onChange={e=>setStop(e.target.value)}/></label></div>}{strategy==='sma_cross'&&<label>TARGET %<input type="number" min="0.1" step="0.1" value={target} onChange={e=>setTarget(e.target.value)}/></label>}<label>CAPITAL PER TRADE (₹)<input type="number" min="1" value={capital} onChange={e=>setCapital(e.target.value)}/></label><button className="primary" disabled={!!job&&['queued','running'].includes(job.status)} onClick={()=>submit('backtests')}><Play size={17}/> Run backtest</button><p className="footnote">No fees or slippage included. If stop and target are both reached within a candle, the stop wins.</p></>}
 </section><section className="panel results"><div className="panelheading rightheading"><div><h2>{tab==='archive'?'Archive coverage':'Run results'}</h2><p>{tab==='archive'?'Stored instruments and available periods.':'Trade statistics and execution log.'}</p></div><button className="plain" onClick={refresh}>Refresh</button></div>
 {job&&<div className="job"><div><span className="joblabel">LATEST JOB · {job.id.slice(0,8)}</span><strong>{job.status.toUpperCase()}</strong></div><div className="progress"><span style={{width:job.total?`${Math.min(100,job.progress/job.total*100)}%`:'5%'}}/></div><small>{job.progress} / {job.total||'…'} windows or instruments</small></div>}
 {tab==='archive'?<>{coverage.length?<div className="tablewrap"><table><thead><tr><th>INSTRUMENT</th><th>PERIOD</th><th>RANGE</th><th className="numeric">CANDLES</th></tr></thead><tbody>{coverage.map((r,i)=><tr key={i}><td>{r.instrument}</td><td><span className="period">{r.interval}</span></td><td>{r.from_date} → {r.to_date}</td><td className="numeric">{r.candles.toLocaleString()}</td></tr>)}</tbody></table></div>:<div className="empty"><Database size={32}/><h3>Archive is empty</h3><p>Add instrument keys and start an import to build your dataset.</p></div>}</>:job?.kind==='backtest'&&job.result?<><div className="resultmetrics"><div><span>TRADES</span><strong>{job.result.summary.trades}</strong></div><div><span>WIN RATE</span><strong>{job.result.summary.win_rate}%</strong></div><div><span>NET P/L</span><strong>₹{job.result.summary.net_pnl.toLocaleString()}</strong></div></div>{job.result.missing_instruments?.length>0&&<div className="alert danger">Missing archive: {job.result.missing_instruments.join(', ')}</div>}<div className="rowtitle">TRADE LOG <button className="plain" onClick={downloadTrades}>Download CSV</button></div><div className="tablewrap"><table><thead><tr><th>SYMBOL</th><th>ENTRY</th><th>EXIT</th><th>REASON</th><th className="numeric">P/L</th></tr></thead><tbody>{job.result.trades.slice(0,100).map((t:any,i:number)=><tr key={i}><td>{t.instrument}</td><td>{t.entry_at.replace('T',' ').slice(0,16)} · ₹{t.entry}</td><td>{t.exit_at.replace('T',' ').slice(0,16)} · ₹{t.exit}</td><td>{t.reason}</td><td className={`numeric ${t.pnl>=0?'profit':'loss'}`}>₹{t.pnl}</td></tr>)}</tbody></table></div>{job.result.trades.length>100&&<p className="footnote">Showing first 100 trades. Download CSV for all trades.</p>}</>:<div className="empty"><Activity size={32}/><h3>No run selected</h3><p>Choose an archived timeframe and run a strategy to see results.</p></div>}
 </section></div></div></main></div>
}
