'use client';
import { useCallback, useEffect, useState } from 'react';
import { Activity, ArrowDownToLine, BarChart3, Database, Play, RefreshCw, Settings2 } from 'lucide-react';

type Archive = {interval:string;instruments:number;candles:number};
type Job = {id:string;kind:string;status:string;progress:number;total:number;result?:any;error?:string;details?:{symbol?:string;symbol_number?:number;symbols_total?:number;interval?:string;windows_done_for_symbol?:number;windows_for_symbol?:number;skipped?:number;candles_added?:number;failed_symbols?:{symbol:string;error:string}[]}};
type Coverage = {instrument:string;symbol:string;interval:string;from_date:string;to_date:string;candles:number;windows:number;first_candle:string|null;last_candle:string|null;filled_windows:number;verified_windows:number};
type ApiKey = {id:string;label:string;account_id:string;expires_at:string|null;status:string;token_type?:string;used?:boolean};
type Candle = {ts:string;open:number;high:number;low:number;close:number;volume:number;open_interest:number|null};
const intervals=['1m','5m','15m','30m','1h','1d','1w','1mo'];
const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
const earlier=new Date(Date.now()-365*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
function errorMessage(value:unknown):string {if(typeof value==='string')return value;if(Array.isArray(value))return value.map(errorMessage).join('; ');if(value&&typeof value==='object'){const detail=value as {msg?:unknown;message?:unknown;detail?:unknown};return errorMessage(detail.msg??detail.message??detail.detail??'Request failed')}return 'Request failed'}
async function api(path:string, body?:unknown) { const r=await fetch(`/api/${path}`,body ? {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(errorMessage(data.detail??data));return data; }
function ApiKeys(){
 const [keys,setKeys]=useState<ApiKey[]>([]);const [label,setLabel]=useState('');const [accountId,setAccountId]=useState('');const [token,setToken]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [limits,setLimits]=useState<{requests_per_minute_per_account:number;parallel_workers:number}|null>(null);
 const reload=useCallback(async()=>{try{const result=await api('api-keys');setKeys(result.keys);setLimits(result)}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{reload()},[reload]);
 async function add(){setBusy(true);setError('');setNotice('');try{const result=await api('api-keys',{label,account_id:accountId,access_token:token});setToken('');setLabel('');setAccountId('');setNotice(`Saved ${result.label} (${result.token_type==='analytics'?'Analytics Token':'daily OAuth token'}).`);await reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(id:string){setBusy(true);setError('');try{const response=await fetch(`/api/api-keys/${encodeURIComponent(id)}`,{method:'DELETE'});const result=await response.json();if(!response.ok)throw new Error(errorMessage(result.detail??result));await reload();setNotice('Access token removed.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel keys-panel"><div className="panelheading"><span className="panelicon"><Settings2 size={18}/></span><div><h2>Upstox account tokens</h2><p>Add Analytics Tokens or daily OAuth tokens. We verify access using the historical candle API used by imports.</p></div></div>
 {limits&&<p className="footnote">Current downloader: {limits.parallel_workers} parallel requests, up to {limits.requests_per_minute_per_account} requests per minute per account (with second and 30 minute safeguards).</p>}
 {error&&<div className="alert danger">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="keylist">{keys.map(key=><div className="keycard" key={key.id}><div><strong>{key.label}</strong><span>Account {key.account_id} · {key.id==='environment'?(key.used?'Railway variable · active':'Railway variable · duplicate or unverified'):key.status==='expired'||(key.expires_at&&Date.parse(key.expires_at)<Date.now())?'Expired':key.token_type==='analytics'?'Analytics · check expiry in Upstox':key.expires_at?`OAuth · expires ${new Date(key.expires_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST`:'Active'}</span></div>{key.id!=='environment'&&<button className="plain" disabled={busy} onClick={()=>remove(key.id)}>Remove</button>}</div>)}{!keys.length&&<p className="footnote">No valid tokens saved yet.</p>}</div>
 <div className="keyform"><label>ACCOUNT LABEL<input value={label} onChange={event=>setLabel(event.target.value)} placeholder="Account 2" maxLength={60}/></label><label>ACCOUNT ID (OPTIONAL)<input value={accountId} onChange={event=>setAccountId(event.target.value)} placeholder="Your Upstox UCC" maxLength={60}/></label><label>ANALYTICS OR OAUTH TOKEN<input type="password" autoComplete="off" value={token} onChange={event=>setToken(event.target.value)} placeholder="Paste the full token"/></label><button className="primary" disabled={busy||!label.trim()||token.trim().length<20} onClick={add}>Verify candle access and save</button></div>
 <p className="footnote">Analytics Tokens are read-only and valid for up to one year; check their exact expiry in Upstox. Daily OAuth tokens expire at 3:30 AM IST. For Analytics Tokens, enter the Upstox account ID to group tokens from the same user under one rate limit. If left blank, the account label is used. Tokens are encrypted on the worker and never returned to this page.</p>
 </section>
}
function CandleViewer({coverage, active, initialInstrument, refresh, onJob}: {coverage:Coverage[];active:boolean;initialInstrument:string;refresh:()=>Promise<void>;onJob:(job:Job)=>void}) {
 const instruments=[...new Set(coverage.map(row=>row.instrument))];
 const [instrument,setInstrument]=useState(initialInstrument);const [interval,setTimeframe]=useState('1m');
 const [end,setEnd]=useState('');const [start,setStart]=useState('');const [appliedStart,setAppliedStart]=useState('');const [appliedEnd,setAppliedEnd]=useState('');const [page,setPage]=useState(1);const [cursors,setCursors]=useState<(string|null)[]>([null]);
 const [result,setResult]=useState<{rows:Candle[];has_more:boolean;next_cursor:string|null}|null>(null);
 const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [tick,setTick]=useState(0);
 const [message,setMessage]=useState('');const [confirmDelete,setConfirmDelete]=useState(false);const [deleteText,setDeleteText]=useState('');const [busy,setBusy]=useState(false);
 const [editingName,setEditingName]=useState(false);const [nameInput,setNameInput]=useState('');
 const current=instruments.includes(instrument)?instrument:(instruments[0]||'');
 const available=intervals.filter(period=>coverage.some(row=>row.instrument===current&&row.interval===period));
 const currentInterval=available.includes(interval)?interval:(available[0]||'');
 const selected=coverage.find(row=>row.instrument===current&&row.interval===currentInterval);
 const label=selected?.symbol||current;
 const selectedCoverage=coverage.filter(row=>row.instrument===current);
 const last=selected?.to_date||'';
 const first=selected?.from_date||'';
 const effectiveStart=start||first;const effectiveEnd=end||last;
 const viewStart=appliedStart||first;const viewEnd=appliedEnd||last;
 const validRange=!!effectiveStart&&!!effectiveEnd&&effectiveStart<=effectiveEnd;
 const [exportProgress,setExportProgress]=useState('');
 useEffect(()=>{if(!active)return;const timer=setInterval(()=>setTick(value=>value+1),10000);return()=>clearInterval(timer)},[active]);
 useEffect(()=>{if(!current||!currentInterval||!viewStart||!viewEnd||viewStart>viewEnd){setResult(null);return}let cancelled=false;setLoading(true);setError('');
  const params=new URLSearchParams({instrument:current,interval:currentInterval,from_date:viewStart,to_date:viewEnd,limit:'100'});if(cursors[page-1])params.set('cursor',cursors[page-1]!);
  api(`candles?${params}`).then(data=>{if(!cancelled)setResult(data)}).catch(err=>{if(!cancelled){setResult(null);setError(err.message)}}).finally(()=>{if(!cancelled)setLoading(false)});
  return()=>{cancelled=true};
 },[current,currentInterval,viewStart,viewEnd,page,cursors,tick]);
 const changeInstrument=(value:string)=>{setInstrument(value);setTimeframe('1m');setStart('');setEnd('');setAppliedStart('');setAppliedEnd('');setPage(1);setCursors([null]);setConfirmDelete(false);setMessage('')};
 const changeInterval=(value:string)=>{setTimeframe(value);setStart('');setEnd('');setAppliedStart('');setAppliedEnd('');setPage(1);setCursors([null])};
 function applyRange(from=effectiveStart,to=effectiveEnd){if(!from||!to||from>to){setError('FROM must be on or before TO.');return}setStart(from);setEnd(to);setAppliedStart(from);setAppliedEnd(to);setPage(1);setCursors([null]);setError('')}
 function recent(days:number){const to=last;const from=new Date(Math.max(Date.parse(first+'T00:00:00Z'),Date.parse(to+'T00:00:00Z')-(days-1)*86400000)).toISOString().slice(0,10);applyRange(from,to)}
 async function exportCsv(){
  setError('');setExportProgress('');if(!validRange){setError('Select a valid FROM and TO date.');return}
  const picker=(window as Window & {showSaveFilePicker?:(options:unknown)=>Promise<{createWritable:()=>Promise<FileSystemWritableFileStream>}>}).showSaveFilePicker;
  if(!picker){setError('Full-range CSV download needs Chrome or Edge on a secure site.');return}
  let file:FileSystemWritableFileStream;
  try{const handle=await picker({suggestedName:`${label}-${currentInterval}-${effectiveStart}-${effectiveEnd}.csv`,types:[{description:'CSV file',accept:{'text/csv':['.csv']}}]});file=await handle.createWritable()}
  catch(e){if((e as DOMException).name!=='AbortError')setError((e as Error).message);return}
  setBusy(true);let completed=false;
  try{
   const endDay=Date.parse(`${effectiveEnd}T00:00:00Z`);let day=Date.parse(`${effectiveStart}T00:00:00Z`);let part=0;
   while(day<=endDay){const lastDay=Math.min(endDay,day+27*86400000);const from=new Date(day).toISOString().slice(0,10);const to=new Date(lastDay).toISOString().slice(0,10);
    setExportProgress(`Downloading ${from} to ${to}…`);
    const params=new URLSearchParams({instrument:current,interval:currentInterval,from_date:from,to_date:to,include_header:String(part===0)});
    const response=await fetch(`/api/candles/export?${params}`,{cache:'no-store'});
    if(!response.ok){const body=await response.json();throw new Error(errorMessage(body.detail??body))}
    if(!response.body)throw new Error('Download stream unavailable.');
    const reader=response.body.getReader();try{while(true){const {done,value}=await reader.read();if(done)break;await file.write(value)}}finally{reader.releaseLock()}
    day=lastDay+86400000;part++;
   }
   await file.close();completed=true;setExportProgress('CSV download complete.');
  }catch(e){setError(`CSV download stopped: ${(e as Error).message}`);setExportProgress('');}
  finally{if(!completed)await file.abort().catch(()=>{});setBusy(false)}
 }
 async function updateSelected(){if(!selected)return;setBusy(true);setError('');setMessage('');try{const queued=await api('backfill',{instruments:[current],intervals:[currentInterval],from_date:selected.from_date,to_date:today,refresh_existing:true});onJob({...queued,kind:'backfill',progress:0,total:0});setMessage(`Updating ${label} ${currentInterval}: refreshing archived windows through today.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function deleteSelected(){setBusy(true);setError('');setMessage('');try{const result=await api('archive/delete',{instrument:current});setConfirmDelete(false);setDeleteText('');setInstrument('');setResult(null);setAppliedStart('');setAppliedEnd('');setCursors([null]);await refresh();setMessage(`Deleted ${label} across all timeframes (${result.deleted_windows} stored windows).`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveName(){setBusy(true);setError('');try{await api('instrument/label',{instrument:current,symbol:nameInput.trim()});await refresh();setEditingName(false);setMessage('Ticker label updated.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel viewer"><div className="panelheading rightheading"><div><h2>Stored market data</h2><p>Review coverage and candle prices by stock and timeframe. Times are shown in IST.</p></div><button className="plain" onClick={()=>{refresh();setTick(value=>value+1)}}>Refresh data</button></div>
  {message&&<div className="alert success">{message}</div>}{error&&<div className="alert danger" role="alert">{error}</div>}
  {instruments.length?<><div className="viewerfilters"><label>SYMBOL<select value={current} onChange={event=>changeInstrument(event.target.value)}>{instruments.map(value=><option key={value} value={value}>{coverage.find(row=>row.instrument===value)?.symbol||value}</option>)}</select></label><label>TIMEFRAME<select value={currentInterval} onChange={event=>changeInterval(event.target.value)}>{available.map(value=><option key={value}>{value}</option>)}</select></label><label>FROM<input type="date" value={effectiveStart} onChange={event=>setStart(event.target.value)}/></label><label>TO<input type="date" value={effectiveEnd} onChange={event=>setEnd(event.target.value)}/></label></div>
  <div className="symbolkey">{label} <button className="plain" onClick={()=>{setNameInput(label===current?'':label);setEditingName(true)}}>Edit name</button><span>{current}</span></div>
  {editingName&&<div className="nameedit"><input aria-label="Ticker name" value={nameInput} onChange={event=>setNameInput(event.target.value)} placeholder="HCLTECH"/><button onClick={saveName} disabled={busy||!nameInput.trim()}>Save name</button><button className="plain" onClick={()=>setEditingName(false)}>Cancel</button></div>}
  <div className="viewerintervals">{available.map(value=><button key={value} className={`chip ${currentInterval===value?'chosen':''}`} onClick={()=>changeInterval(value)}>{value}</button>)}</div>
  <div className="viewerstats"><div><span>SELECTED CANDLES</span><strong>{(selected?.candles||0).toLocaleString()}</strong></div><div><span>STORED WINDOWS</span><strong>{selected?.windows||0}</strong></div><div><span>FIRST CANDLE</span><strong>{selected?.first_candle||(selected?.filled_windows?'Scanning…':'No candles')}</strong></div><div><span>LATEST CANDLE</span><strong>{selected?.last_candle||(selected?.filled_windows?'Scanning…':'No candles')}</strong></div></div>
  <div className="vieweractions"><button onClick={exportCsv} disabled={busy||!validRange}>Download selected range CSV</button><button onClick={updateSelected} disabled={busy||active}>Update {label} · {currentInterval}</button><button className="deletebutton" onClick={()=>{setConfirmDelete(true);setDeleteText('')}} disabled={busy||active}>Delete {label} data</button></div>{exportProgress&&<p className="footnote" role="status">{exportProgress}</p>}
  {confirmDelete&&<div className="deleteconfirm"><strong>Delete all stored data for {label}?</strong><p>This removes every timeframe and its Parquet files. Type <b>{label}</b> to confirm.</p><div><input aria-label="Confirm symbol" value={deleteText} onChange={event=>setDeleteText(event.target.value)} placeholder={label}/><button className="deletebutton" disabled={busy||deleteText!==label} onClick={deleteSelected}>Delete all data</button><button className="plain" onClick={()=>setConfirmDelete(false)}>Cancel</button></div></div>}
  <div className="rowtitle">ARCHIVE BY TIMEFRAME <span>{selectedCoverage.reduce((sum,row)=>sum+row.candles,0).toLocaleString()} candles across {selectedCoverage.length} periods</span></div>
  <div className="tablewrap coveragebreakdown"><table><thead><tr><th>TIMEFRAME</th><th>FIRST PRICE DATE</th><th>LAST PRICE DATE</th><th>REQUESTED RANGE</th><th className="numeric">WINDOWS</th><th className="numeric">CANDLES</th><th></th></tr></thead><tbody>{selectedCoverage.map(row=><tr key={row.interval}><td><span className="period">{row.interval}</span></td><td>{row.first_candle||(row.filled_windows?'Scanning…':'No candles')}</td><td>{row.last_candle||(row.filled_windows?'Scanning…':'No candles')}</td><td>{row.from_date} → {row.to_date}</td><td className="numeric">{row.verified_windows}/{row.filled_windows} verified</td><td className="numeric">{row.candles.toLocaleString()}</td><td><button className="plain" onClick={()=>changeInterval(row.interval)}>View prices</button></td></tr>)}</tbody></table></div>
  <p className="footnote">Minute data is fetched in 28 day API requests and stored across the full selected import range. Select any stored date range to view or export. Full-range CSV writes directly to a file in Chrome or Edge; keep this tab open until complete.</p>
  <div className="rowtitle candleheading">PRICE ROWS <span>{viewStart} → {viewEnd} · {currentInterval} · newest first</span></div>
  <div className="rangecontrols"><div><button className="plain" onClick={()=>recent(7)}>7 days</button><button className="plain" onClick={()=>recent(31)}>1 month</button><button className="plain" onClick={()=>recent(365)}>1 year</button><button className="plain" onClick={()=>applyRange(first,last)}>All stored dates</button></div><button className="applyrange" onClick={()=>applyRange()} disabled={!validRange}>Apply date range</button></div>
  {!validRange&&<div className="alert danger">FROM must be on or before TO. Change either date, then click Apply date range.</div>}
  {loading&&<p className="footnote">Loading stored candles…</p>}
  {result&&<><div className="tablewrap"><table><thead><tr><th>DATE / TIME (IST)</th><th className="numeric">OPEN</th><th className="numeric">HIGH</th><th className="numeric">LOW</th><th className="numeric">CLOSE</th><th className="numeric">VOLUME</th><th className="numeric">OPEN INTEREST</th></tr></thead><tbody>{result.rows.map(row=><tr key={row.ts}><td>{row.ts.slice(0,16).replace('T',' ')}</td><td className="numeric">{row.open}</td><td className="numeric">{row.high}</td><td className="numeric">{row.low}</td><td className="numeric">{row.close}</td><td className="numeric">{row.volume.toLocaleString()}</td><td className="numeric">{row.open_interest?.toLocaleString()??'—'}</td></tr>)}</tbody></table></div>{!result.rows.length&&<div className="empty"><h3>No candles in this date range</h3><p>Try another range or timeframe.</p></div>}<div className="pagination"><span>Page {page} · {result.rows.length} rows shown · {viewStart} to {viewEnd}</span><div><button className="plain" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button className="plain" disabled={!result.has_more} onClick={()=>{setCursors([...cursors.slice(0,page),result.next_cursor]);setPage(page+1)}}>Next</button></div></div></>}
  </>:<div className="empty"><Database size={32}/><h3>No stored candles yet</h3><p>Start an import in Data archive, then return here to inspect each timeframe.</p></div>}
 </section>
}
export default function Home(){
 const [tab,setTab]=useState<'archive'|'viewer'|'backtest'|'keys'>('archive');const [viewerInstrument,setViewerInstrument]=useState('');
 const [status,setStatus]=useState<{archive:Archive[];active_jobs:number}|null>(null);
 const [coverage,setCoverage]=useState<Coverage[]>([]);
 const [error,setError]=useState('');const [notice,setNotice]=useState('');const [job,setJob]=useState<Job|null>(null);
 const [symbols,setSymbols]=useState('NSE_EQ|INE002A01018');const [selected,setSelected]=useState<string[]>(['1m','5m','15m','30m','1h','1d','1w','1mo']);
 const [useTop1000,setUseTop1000]=useState(false);const [universeInfo,setUniverseInfo]=useState<{count:number;as_of:string;method:string}|null>(null);
 const [from,setFrom]=useState(earlier);const [to,setTo]=useState(today);const [period,setPeriod]=useState('1m');const [strategy,setStrategy]=useState('dip_buy');
 const [dip,setDip]=useState('3');const [target,setTarget]=useState('2');const [stop,setStop]=useState('1');const [capital,setCapital]=useState('10000');const [fast,setFast]=useState('10');const [slow,setSlow]=useState('30');
 const refresh=useCallback(async()=>{try { const [a,b]=await Promise.all([api('status'),api('symbols')]);setStatus(a);setCoverage(b.symbols); }catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{api('universes/top100mc').then(setUniverseInfo).catch(()=>{})},[]);
 useEffect(()=>{refresh();const saved=localStorage.getItem('backtest-desk-job');if(saved)api(`jobs/${saved}`).then((latest:Job)=>{setJob(latest);if(latest.status==='failed')setError(latest.error||'Job failed without an error message. Retry after the worker update.');}).catch(()=>localStorage.removeItem('backtest-desk-job'))},[refresh]);
 useEffect(()=>{if(job?.id)localStorage.setItem('backtest-desk-job',job.id)},[job?.id]);
 useEffect(()=>{if(!job||!['queued','running'].includes(job.status))return;const timer=setInterval(async()=>{try{const next=await api(`jobs/${job.id}`);setJob(next);if(next.kind==='backfill'&&next.details?.symbol_number!==job.details?.symbol_number)refresh();if(next.status==='complete'){setNotice(next.kind==='backfill'?'Import completed.':'Backtest completed.');refresh();}if(next.status==='partial'){setNotice('Import finished with some symbols unavailable. Review the failures below and retry later.');refresh();}if(next.status==='failed'){setError(next.error||'Import paused. Resume after resolving the issue.');refresh();}}catch(e){setError((e as Error).message)}},2000);return()=>clearInterval(timer)},[job,refresh]);
 function parsed(){return [...new Set(symbols.split(/[\s,]+/).map(s=>s.trim()).filter(Boolean))]}
 async function submit(kind:'backfill'|'backtests'){setError('');setNotice('');if(!useTop1000&&!parsed().length){setError('Add at least one ticker or instrument key.');return}try{const payload=kind==='backfill'?{instruments:useTop1000?[]:parsed(),universe:useTop1000?'top100mc':undefined,intervals:selected,from_date:from,to_date:to}:{instruments:parsed(),interval:period,from_date:from,to_date:to,strategy,dip_pct:Number(dip),target_pct:Number(target),stop_pct:Number(stop),capital_per_trade:Number(capital),fast:Number(fast),slow:Number(slow)};const result=await api(kind,payload);setJob({...result,kind,progress:0,total:0});setNotice('Job queued. Completed windows are saved; a failed import can be resumed.');}catch(e){setError((e as Error).message)}}
 async function resumeImport(){if(!job)return;try{const next=await api(`jobs/${job.id}/resume`,{});setJob({...job,...next,error:undefined});setError('');setNotice('Resuming import. Stored windows will be skipped.')}catch(e){setError((e as Error).message)}}
 function downloadTrades(){if(!job?.result?.trades)return;const t=job.result.trades;const cols=['instrument','entry_at','entry','exit_at','exit','quantity','reason','pnl','return_pct'];const csv=[cols.join(','),...t.map((r:Record<string,unknown>)=>cols.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download=`backtest-${job.id}.csv`;link.click();URL.revokeObjectURL(link.href)}
 const total=status?.archive.reduce((sum,a)=>sum+a.candles,0)||0;
 const jobFailures=job?.details?.failed_symbols||[];
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandmark"><BarChart3 size={21}/></div><div><strong>BACKTEST DESK</strong><span>UPSTOX RESEARCH</span></div></div><div className="navlabel">WORKSPACE</div><button className={`nav ${tab==='archive'?'active':''}`} onClick={()=>setTab('archive')}><Database size={18}/> Data archive</button><button className={`nav ${tab==='viewer'?'active':''}`} onClick={()=>setTab('viewer')}><BarChart3 size={18}/> Data Viewer</button><button className={`nav ${tab==='backtest'?'active':''}`} onClick={()=>setTab('backtest')}><Activity size={18}/> Backtests</button><button className={`nav ${tab==='keys'?'active':''}`} onClick={()=>setTab('keys')}><Settings2 size={18}/> API Keys</button><div className="sidebarbottom"><span className={`statusdot ${status?'online':''}`}/>{status?'Worker connected':'Worker unavailable'}<small>Data stays on the server</small></div></aside>
 <main className="main"><header className="topbar"><div className="crumb">RESEARCH / {tab==='archive'?'DATA ARCHIVE':tab==='viewer'?'DATA VIEWER':tab==='keys'?'API KEYS':'BACKTESTS'}</div><div className="topactions"><button className="plain" onClick={()=>setTab('keys')}><Settings2 size={15}/> API Keys</button><button className="iconbutton" onClick={refresh} aria-label="Refresh data"><RefreshCw size={17}/></button></div></header>
 <div className="content"><div className="heading"><div><div className="eyebrow">MARKET DATA WORKSPACE</div><h1>{tab==='archive'?'Data archive':tab==='viewer'?'Data Viewer':tab==='keys'?'API Keys':'Strategy backtests'}</h1><p>{tab==='archive'?'Import Upstox candles and keep each timeframe in its own Parquet dataset.':tab==='viewer'?'See the actual available dates and prices for each timeframe.':tab==='keys'?'Add access tokens for your Upstox accounts to speed up downloads.':'Run candle-based strategies against your stored data.'}</p></div><div className="timebadge">NSE · ASIA/KOLKATA</div></div>
 {error&&<div className="alert danger" role="alert">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="metrics"><div className="metric"><span>STORED CANDLES</span><strong>{total.toLocaleString()}</strong><small>Across all timeframes</small></div><div className="metric"><span>INSTRUMENTS</span><strong>{new Set(coverage.map(x=>x.instrument)).size}</strong><small>With archived data</small></div><div className="metric"><span>ACTIVE JOBS</span><strong>{status?.active_jobs??'—'}</strong><small>Queued or running</small></div></div>
 {tab==='keys'?<ApiKeys/>:tab==='viewer'?<CandleViewer coverage={coverage} active={!!job&&['queued','running'].includes(job.status)} initialInstrument={viewerInstrument} refresh={refresh} onJob={setJob}/>:<div className="grid"><section className="panel controls"><div className="panelheading"><span className="panelicon"><Settings2 size={18}/></span><div><h2>{tab==='archive'?'New data import':'Configure run'}</h2><p>{tab==='archive'?'Existing windows are skipped on repeat imports.':'Signals execute at the following candle open.'}</p></div></div>
 {tab==='archive'&&<label className="universechoice"><input type="checkbox" checked={useTop1000} onChange={e=>setUseTop1000(e.target.checked)}/> Use saved top100mc · {universeInfo?.count??'1,000'} NSE stocks <small>Frozen June 2026 AMFI NSE average market-cap ranking. Import one symbol at a time across every selected interval.</small></label>}
 {!useTop1000&&<label>NSE TICKERS OR UPSTOX INSTRUMENT KEYS<textarea value={symbols} onChange={e=>setSymbols(e.target.value)} rows={3} placeholder="RELIANCE, TCS or NSE_EQ|INE002A01018"/><small>Separate entries with commas, spaces, or new lines. Tickers resolve inside the import job for large lists.</small></label>}
 <div className="fields"><label>FROM<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>TO<input type="date" value={to} min={from} max={today} onChange={e=>setTo(e.target.value)}/></label></div>
 {tab==='archive'?<><div className="fieldtitle">TIMEFRAMES <span>{selected.length} selected</span></div><div className="chips">{intervals.map(p=><button key={p} className={`chip ${selected.includes(p)?'chosen':''}`} onClick={()=>setSelected(selected.includes(p)?selected.filter(v=>v!==p):[...selected,p])}>{p}</button>)}</div><button className="primary" disabled={!selected.length||!!job&&['queued','running'].includes(job.status)} onClick={()=>submit('backfill')}><ArrowDownToLine size={17}/> Start import</button></>:<><div className="fields"><label>TIMEFRAME<select value={period} onChange={e=>setPeriod(e.target.value)}>{intervals.map(p=><option key={p}>{p}</option>)}</select></label><label>STRATEGY<select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="dip_buy">Dip from previous close</option><option value="sma_cross">SMA crossover</option></select></label></div>{strategy==='dip_buy'?<div className="fields three"><label>DIP %<input type="number" min="0.1" step="0.1" value={dip} onChange={e=>setDip(e.target.value)}/></label><label>TARGET %<input type="number" min="0.1" step="0.1" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>STOP %<input type="number" min="0.1" step="0.1" value={stop} onChange={e=>setStop(e.target.value)}/></label></div>:<div className="fields three"><label>FAST SMA<input type="number" min="2" value={fast} onChange={e=>setFast(e.target.value)}/></label><label>SLOW SMA<input type="number" min="3" value={slow} onChange={e=>setSlow(e.target.value)}/></label><label>STOP %<input type="number" min="0.1" step="0.1" value={stop} onChange={e=>setStop(e.target.value)}/></label></div>}{strategy==='sma_cross'&&<label>TARGET %<input type="number" min="0.1" step="0.1" value={target} onChange={e=>setTarget(e.target.value)}/></label>}<label>CAPITAL PER TRADE (₹)<input type="number" min="1" value={capital} onChange={e=>setCapital(e.target.value)}/></label><button className="primary" disabled={!!job&&['queued','running'].includes(job.status)} onClick={()=>submit('backtests')}><Play size={17}/> Run backtest</button><p className="footnote">No fees or slippage included. If stop and target are both reached within a candle, the stop wins.</p></>}
 </section><section className="panel results"><div className="panelheading rightheading"><div><h2>{tab==='archive'?'Archive coverage':'Run results'}</h2><p>{tab==='archive'?'Stored instruments and available periods.':'Trade statistics and execution log.'}</p></div><button className="plain" onClick={refresh}>Refresh</button></div>
 {job&&<div className="job"><div><span className="joblabel">LATEST JOB · {job.id.slice(0,8)}</span><strong>{job.status.toUpperCase()}</strong></div><div className="progress"><span style={{width:job.total?`${Math.min(100,job.progress/job.total*100)}%`:'5%'}}/></div><small>{job.progress.toLocaleString()} / {job.total?.toLocaleString()||'…'} windows · {job.total?Math.round(job.progress/job.total*100):0}%</small>{job.kind==='backfill'&&job.details?.symbol&&<p className="jobdetail">Stock {job.details.symbol_number} / {job.details.symbols_total}: <b>{job.details.symbol}</b> · {job.details.interval||'starting'} · {job.details.windows_done_for_symbol||0} / {job.details.windows_for_symbol} windows · {job.details.skipped||0} already stored</p>}{jobFailures.length>0&&<details><summary>{jobFailures.length} unavailable symbols</summary><div className="failures">{jobFailures.map((item,i)=><p key={i}>{item.symbol}: {item.error}</p>)}</div></details>}{job.kind==='backfill'&&['failed','partial'].includes(job.status)&&<button className="primary" onClick={resumeImport}>Resume from stored windows</button>}</div>}
 {tab==='archive'?<>{coverage.length?<div className="tablewrap"><table><thead><tr><th>INSTRUMENT</th><th>PERIOD</th><th>RANGE</th><th className="numeric">CANDLES</th></tr></thead><tbody>{coverage.map((r,i)=><tr key={i}><td><button className="plain symbolbutton" onClick={()=>{setViewerInstrument(r.instrument);setTab('viewer')}}>{r.symbol||r.instrument}</button><small className="instrumentkey">{r.instrument}</small></td><td><span className="period">{r.interval}</span></td><td>{r.from_date} → {r.to_date}</td><td className="numeric">{r.candles.toLocaleString()}</td></tr>)}</tbody></table></div>:<div className="empty"><Database size={32}/><h3>Archive is empty</h3><p>Add instrument keys and start an import to build your dataset.</p></div>}</>:job?.kind==='backtest'&&job.result?<><div className="resultmetrics"><div><span>TRADES</span><strong>{job.result.summary.trades}</strong></div><div><span>WIN RATE</span><strong>{job.result.summary.win_rate}%</strong></div><div><span>NET P/L</span><strong>₹{job.result.summary.net_pnl.toLocaleString()}</strong></div></div>{job.result.missing_instruments?.length>0&&<div className="alert danger">Missing archive: {job.result.missing_instruments.join(', ')}</div>}<div className="rowtitle">TRADE LOG <button className="plain" onClick={downloadTrades}>Download CSV</button></div><div className="tablewrap"><table><thead><tr><th>SYMBOL</th><th>ENTRY</th><th>EXIT</th><th>REASON</th><th className="numeric">P/L</th></tr></thead><tbody>{job.result.trades.slice(0,100).map((t:any,i:number)=><tr key={i}><td>{t.instrument}</td><td>{t.entry_at.replace('T',' ').slice(0,16)} · ₹{t.entry}</td><td>{t.exit_at.replace('T',' ').slice(0,16)} · ₹{t.exit}</td><td>{t.reason}</td><td className={`numeric ${t.pnl>=0?'profit':'loss'}`}>₹{t.pnl}</td></tr>)}</tbody></table></div>{job.result.trades.length>100&&<p className="footnote">Showing first 100 trades. Download CSV for all trades.</p>}</>:<div className="empty"><Activity size={32}/><h3>No run selected</h3><p>Choose an archived timeframe and run a strategy to see results.</p></div>}
 </section></div>}</div></main></div>
}
